# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 060fc90570efe51759f676f8e3d59e7a71ae9055d0876cdcd12ce09a417c34d13fccaaedc5a02bdd14510379a767a3cf772d631050b8d96ee94803bce1fc0acd

test:
  secret_key_base: 647750cd7901919bccccfaf45f0861c268ea873ae4a60749d4e87a61c176bfe02b78a12f40175f0c3a0b20f1833ee65ff5d4bad0161be5501374b04d3f340157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
